version: 1
formatters:
  simple:
    format: "%(asctime)s  %(filename)s line:%(lineno)s: %(message)s"
  full:
    format: "%(asctime)s  %(filename)s[line:%(lineno)d] - %(levelname)s:  %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: full
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: full
    level: DEBUG
    filename: logging/info.log
    maxBytes:  10485760 # 10M
    backupCount: 20
    encoding: utf8
  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: full
    filename: logging/error.log
    maxBytes: 10485760 # 10M
    backupCount: 20
    encoding: utf8
loggers:
  main.core:
    level: DEBUG
    handlers: [console, file, error]
root:
  level: DEBUG
  handlers: [console,file,error]